language: php

dist: trusty

sudo: required

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: 7.2
    - php: nightly
  fast_finish: true

before_install:
  - ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -P ""
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - chmod 0600 ~/.ssh/{authorized_keys,id_rsa,id_rsa.pub}
  - eval "$(ssh-agent -s)" #start the ssh agent
  - ssh-add
  - composer self-update

install:
  - travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest

script:
  - vendor/bin/phpunit
